import { supabaseServer } from "@/lib/supabase/server";

export default async function AccountDetailsPage(props: { params: { id: string } }) {
  const { params } = props;
    const id = params.id;

      const supabase = supabaseServer();

        const { data: account, error } = await supabase
            .from("accounts")
                .select("*")
                    .eq("id", id)
                        .single();

                          if (error) {
                              return (
                                    <div style={{ padding: 40, color: "red" }}>
                                            Supabase error: {error.message}
                                                  </div>
                                                      );
                                                        }

                                                          if (!account) {
                                                              return (
                                                                    <div style={{ padding: 40, color: "red" }}>
                                                                            Account not found<br />
                                                                                    ID recebido: {id}
                                                                                          </div>
                                                                                              );
                                                                                                }

                                                                                                  return (
                                                                                                      <div
                                                                                                            style={{
                                                                                                                    minHeight: "100vh",
                                                                                                                            background: "#0d0d0d",
                                                                                                                                    color: "#fff",
                                                                                                                                            padding: "60px 40px",
                                                                                                                                                    fontFamily: "Inter, sans-serif",
                                                                                                                                                          }}
                                                                                                                                                              >
                                                                                                                                                                    <a
                                                                                                                                                                            href="/accounts"
                                                                                                                                                                                    style={{
                                                                                                                                                                                              display: "inline-block",
                                                                                                                                                                                                        marginBottom: "30px",
                                                                                                                                                                                                                  background: "#1a1a1a",
                                                                                                                                                                                                                            color: "#fff",
                                                                                                                                                                                                                                      padding: "10px 16px",
                                                                                                                                                                                                                                                borderRadius: "8px",
                                                                                                                                                                                                                                                          border: "1px solid #333",
                                                                                                                                                                                                                                                                    textDecoration: "none",
                                                                                                                                                                                                                                                                              fontSize: "14px",
                                                                                                                                                                                                                                                                                        opacity: 0.8,
                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                              ← Back
                                                                                                                                                                                                                                                                                                                    </a>

                                                                                                                                                                                                                                                                                                                          <h1 style={{ fontSize: 36, fontWeight: 700, color: "#f7931a" }}>
                                                                                                                                                                                                                                                                                                                                  {account.name}
                                                                                                                                                                                                                                                                                                                                        </h1>

                                                                                                                                                                                                                                                                                                                                              <div
                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                background: "#1a1a1a",
                                                                                                                                                                                                                                                                                                                                                                          padding: 30,
                                                                                                                                                                                                                                                                                                                                                                                    borderRadius: 12,
                                                                                                                                                                                                                                                                                                                                                                                              border: "1px solid #262626",
                                                                                                                                                                                                                                                                                                                                                                                                        maxWidth: 500,
                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: 40,
                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                        <p><strong>Category:</strong> {account.category}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <p><strong>Provider:</strong> {account.provider}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p><strong>Type:</strong> {account.account_type}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p><strong>Currency:</strong> {account.currency_base}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p><strong>Created:</strong> {new Date(account.created_at).toLocaleString()}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    